services:
  mysql:
    image: mysql
    ports:
      -"3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSOWORD=123
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSOWORD=123